#配置选择 dev:开发环境 | test:测试环境 | pro:生产环境
spring.profiles.active: dev
#spring banner
spring.main.banner-mode: off
#mybatis-plus banner
mybatis-plus.global-config.banner: off
#数据库驱动名
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#服务名称
spring.application.name: xfile
#database
database.name: ${spring.application.name}
# 日志配置
logging:
  file:
    # 日志文件名格式
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  pattern:
    # 日志记录格式[时间戳] [日志级别] [类名.方法名] [消息文本]
    #file: xfile-%d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
    file: xfile-%d{yyyy-MM-dd HH:mm:ss} %p %C.%M %m %n
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过10MB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ${user.home}/logs/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB)
      max-file-size: 1MB
      # 要保留的日志备份的总大小(默认为0B)
      total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      max-history: 30
#flyway
spring.flyway:
  # 启用或禁用 flyway
  enabled: true
  # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
  clean-disabled: true
  # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
  locations: classpath:db/migration
  #  metadata 版本控制信息表 默认 flyway_schema_history
  table: flyway_schema_history
  # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
  # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
  baseline-on-migrate: true
  # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
  baseline-version: 1
  # 字符编码 默认 UTF-8
  encoding: UTF-8
  # 是否允许不按顺序迁移 开发建议 true  生产建议 false
  out-of-order: false
  # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
  # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
  # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
  schemas: ${database.name}
  # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
  validate-on-migrate: true
---
#应用服务WEB访问端口
server.port: 8080

spring:
  config:
    activate:
      on-profile: dev
  #数据库配置
  datasource:
    #MysqlUrl格式: jdbc:mysql://IP:Port/DataBaseName?parameter=value
    url: jdbc:mysql://localhost:3306/${database.name}
    #数据库用户名
    username: root
    #数据库密码
    password: 123456

#mybatis-plus
mybatis-plus:
  configuration:
    #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰转换
    #map-underscore-to-camel-case: false
logging:
  level:
    root: error
    sql: info
    web: warn